server:
  port: ${CONNECT4_LISTENING_PORT}

database:
  host: ${CONNECT4_DATABASE_HOST}
  port: ${CONNECT4_DATABASE_PORT}
  name: ${CONNECT4_DATABASE_NAME}
  user: ${CONNECT4_DATABASE_USER}
  password: ${CONNECT4_DATABASE_PASSWORD}

jwt:
  secret: ${CONNECT4_JWT_SECRET}
  config:
    issuer: ${CONNECT4_JWT_ISSUER:-io:dksifoua:connect4}
    audience: ${CONNECT4_JWT_AUDIENCE:-io:dksifoua:connect4}
    algorithm: ${CONNECT4_JWT_ALGORITHM:-HS256}
    expiresIn: ${CONNECT4_JWT_EXPIRES_IN}