### Register Dimitri
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "Dimitri",
    "password": "Password123"
}

### Login Dimitri
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Dimitri",
  "password": "Password123"
}

