###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NjY5NzYzNTgsImlzcyI6ImlvOmRrc2lmb3VhOmNvbm5lY3Q0IiwiYXVkIjoiaW86ZGtzaWZvdWE6Y29ubmVjdDQiLCJzdWIiOiJEaW1pdHJpIiwianRpIjoiYjY3YjcwZDctMGNhOC00NjZkLTk1ZWUtYzAzOTUwMDVmNWQwIiwiZXhwIjoxNzY2OTc5OTU4fQ.hEQbZIDwOtuzMNON2oHpPOudrAxwUg73RZqD8fOaK5M
