###
GET http://localhost:3000/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjY5NzMxMjYsImlzcyI6ImlvOmRrc2lmb3VhOmNvbm5lY3Q0IiwiYXVkIjoiaW86ZGtzaWZvdWE6Y29ubmVjdDQiLCJzdWIiOiJEaW1pdHJpIiwianRpIjoiNDAyYWQ3NmItY2MyMS00MzZmLWE1NzMtZWFmYzBhMDZlNjkyIiwiZXhwIjoxNzY2OTc2NzI2fQ.fFAiDcG4sJSjqVmSAfv3Mb1pk6aC5HZb9AIHoFZ-Gz4